[project]
name = "chunkingstrategies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Budhil Thijm", email = "71571047+TimeBudhil@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
chunkingstrategies = "chunkingstrategies:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
